#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=00:15:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=2   # number of nodes
#SBATCH --ntasks-per-node=3   # We use 3 tasks per node for this workload
#SBATCH --job-name="cuda_gemm"
##SBATCH --mail-type=BEGIN
#SBATCH --partition=instruction
#SBATCH --gres=gpu:1

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE

module load cuda 
# run 3 threads per node
mpirun -np 6 ./mmult
echo $(hostname)

